name: Alias
main: JavierLeon9966\Alias\Alias
author: Javier Leon9966
version: 1.0.2
api: [3.0.0]
mcpe-protocol: [223, 261, 274, 282, 291, 313, 332, 340, 354, 361, 388, 389, 390, 407, 408, 419, 422, 428, 431]
description: Detects players possible alternatives accounts
website: https://github.com/JavierLeon9966/Alias
permissions:
  alias.command.alias:
    description: "Allows the user to see another player's possible accounts"
    default: op
  alias.alerts:
    description: "Allows the user to receive alerts when a player joined with a alternative account"
    default: op
